exp_name: 'baseline_mcs'
outdir: './experiments/'

cuda_id: '0'

dataset:
    train_annotation_main: './lists/baseline_exp/train.json'
    val_annotation_main: './lists/baseline_exp/val.json'
    seed: 123
    num_of_classes: 7
    input_size: 224
    crop_size: 2.5
    batch_size: 48
    augmentations: 'default'
    augmentations_valid: 'default'
    num_workers: 16

model:
    model_type: 'resnet34'

train:
    optimizer: 'SGD'
    learning_rate: 0.002
    momentum: 0.9
    lr_schedule: 'cosine'
    n_epoch: 21
    label_smoothing: true
    eps: 0.01
    freq_vis: 500
